Algoritmo "semnome"
// Disciplina   : [Fundamentos da progamação]
// Professor   : Telmo Oliveira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/11/2024


//melhore suas porcentagens!!
Var
salario : real


Inicio
escreval("Diga um salario")
leia(salario)
salario := salario * 1.1 //Melhor do que usar (100/10) salario
escreval(salario)


Fimalgoritmo