Algoritmo "VetorPara"
// Disciplina   : [Fundamentos da progamação]
// Professor   : Telmo Oliveira
// Autor(a)    : Vitor Oliveira Costa Dias
// Data atual  : 20/01/2025

//Vetor sem laço de repetição é zero.
//são dois assunots profundamente interligados interligados.
Var
   vNumeros : vetor[1..10] de inteiro
   i : inteiro


Inicio
   para i de 1 ate 10 faca
      vNumeros[i] := randi(9)
   fimpara

   para i de 1 ate 10 faca
      escreval(vNumeros[i])
   fimpara


Fimalgoritmo