Algoritmo "aula2 Exeplo"
// Disciplina   : [Fundamentos da progamação]
// Professor   : Telmo Oliveira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/11/2024
Var
x : inteiro


Inicio
escreval("Qual o valor de x?")
leia(x)

se x > 10 entao
   escreva("x é maior q 10")
senao
   escreva("x é menor ou igual a 10")
fimse

Fimalgoritmo